# Generated by Django 5.1.2 on 2024-11-20 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('journal', models.TextField()),
                ('happiness', models.IntegerField(choices=[(1, 'Very Unhappy'), (2, 'Unhappy'), (3, 'Neutral'), (4, 'Happy'), (5, 'Very Happy')], default=3)),
                ('img', models.ImageField(blank=True, upload_to='pics')),
                ('audio', models.FileField(blank=True, upload_to='audio')),
                ('location', models.CharField(blank=True, max_length=50)),
                ('additional', models.FileField(blank=True, upload_to='extras')),
            ],
        ),
       
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
