# Generated by Django 5.1.2 on 2024-11-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_journalentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='happiness',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='happiness',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
